name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '20' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.Java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt
          cache: gradle
      - name: Run the tests with Gradle
        run: ./gradlew clean build --console=plain --no-daemon
