name: Publish package to the Maven Central Repository
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew clean build --console=plain --no-daemon
    - name: Publish to Maven central
      run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository  --console=plain --no-daemon
      env:
        SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME}}
        SONATYPE_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
